include: package:flutter_lints/flutter.yaml

linter:
  rules:
    non_constant_identifier_names: false
    avoid_print: false
    empty_catches: false
analyzer:
  errors:
    avoid_print: ignore
    must_be_immutable: ignore
    library_private_types_in_public_api: ignore
    deprecated_member_use: ignore
    unused_local_variable: ignore
    depend_on_referenced_packages: ignore
    file_names: ignore
