name: mabuhay
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1
  page_route_animator: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/icons/common/
  fonts:
    - family: Edmondsans
      fonts:
        - asset: fonts/EdmondsansRegular.ttf
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplayRegular.ttf
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf
